# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-05 22:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mysites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobwebsite',
            name='url',
            field=models.URLField(default=datetime.datetime(2016, 2, 5, 22, 55, 49, 17467, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
